name: GitHub Actions Test
on: [push]
jobs:
  Build-Qt-App:
    runs-on: windows-latest

    env:
      VCINSTALLDIR: 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC'
      QT_VERSION: 5.15.2
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          submodules: true

      - name: Cache Qt
        uses: actions/cache@v1
        id: cache-qt-windows
        with:
          path: ${{ runner.workspace }}/Qt
          key: ${{ runner.os }}-Qt.${{ env.QT_VERSION }}

      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: ${{env.QT_VERSION}}
          target: 'desktop'
          arch: 'win32_msvc2019'
          cached: ${{ steps.cache-qt-windows.outputs.cache-hit }}

      - name: Set up build environment
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: amd64_x86

      - name: Build
        shell: bash
        run: ./.ci/build.sh

      - name: Create zip
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          filename: 'QtWidgetsApp.zip'
          directory: 'build'
          path: 'QtWidgetsApp'

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: my-zip
          path: build/QtWidgetsApp.zip